# 1. Define the Secret
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: bXktdXNlcg==  # base64-encoded 'my-user'
  password: bXktcGFzcw==   # base64-encoded 'my-pass'

---
# 2. Define the Pod that uses the Secret in different ways
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx

    # Option 1: Use secret keys as individual environment variables
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret  # The name of the secret
          key: username    # The specific key in the secret
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password

    # Option 2: Use envFrom to load all secret keys as environment variables
    envFrom:
    - secretRef:
        name: my-secret

    # Option 3: Mount secret as a volume
    volumeMounts:
    - name: secret-volume
      mountPath: "/etc/secret-volume"
      readOnly: true

  # Define the volume that contains the secret
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret  # The name of the secret
