apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  namespace: other-namespace
data:
  config-key: "config-value"

-------------------
apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
  - name: mycontainer
    image: nginx
    env:
    - name: CONFIG_ENV_VAR
      valueFrom:
        configMapKeyRef:
          name: myconfigmap
          key: config-key
          optional: false
    volumeMounts:
    - name: config-volume
      mountPath: "/etc/config-volume"
      readOnly: true
  volumes:
  - name: config-volume
    configMap:
      name: myconfigmap
      namespace: other-namespace
